/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.PanelesPRINCIPALES;

import GUI.FramePrincipal;
import GUI.PanelesInternos.Items.ComprarItem.ComprarItemJPanel;
import GUI.PanelesInternos.Items.VenderItemJPanel;
import GUI.PanelesInternos.Stocks.VerStockJPanel;
import ImagenesHelpers.ImagenesHelper;
import ImagenesHelpers.PanelDeFondo;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Santi-kun
 */
public class PanelDeStock extends javax.swing.JPanel {
 private void montarMenuLateralReutilizable() {
        MenuLateral.removeAll();
        MenuLateral.setLayout(new BorderLayout());
        MenuLateral.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 2, Color.BLACK));

        PanelLateral lateral = new PanelLateral();   // tu menú reusable real
        MenuLateral.add(lateral, BorderLayout.CENTER);

        MenuLateral.revalidate();
        MenuLateral.repaint();
    }
    /**
     * Creates new form PanelDeStock
     */
    public PanelDeStock() {
        initComponents();
        int anchoMenuLateral = 220; 
        MenuLateral.setPreferredSize(new java.awt.Dimension(anchoMenuLateral, 0));
        MenuLateral.setMinimumSize(new java.awt.Dimension(anchoMenuLateral, 0));
        montarMenuLateralReutilizable();
        //CONFIURO EL FONDO PARA QUE SE VEA TODO JUNTO SIN SEPARACION
        Fondo.removeAll();
        Fondo.setLayout(new BorderLayout(0, 0));
        Fondo.setBorder(new EmptyBorder(0,0,0,0));

        MenuLateral.setBorder(new EmptyBorder(0,0,0,0));
        MenuSuperior.setBorder(new EmptyBorder(0,0,0,0));
        Integer alturaMenuSuperior = 100;
        MenuSuperior.setPreferredSize(new java.awt.Dimension(0, alturaMenuSuperior)); // probá 120..160
        MenuSuperior.setMinimumSize(new java.awt.Dimension(0, alturaMenuSuperior));
        MenuSuperior.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, alturaMenuSuperior));
        Contenido.setBorder(new EmptyBorder(0,0,0,0));
        int grosor = 2;

        MenuSuperior.setBorder(BorderFactory.createMatteBorder(0, 0, grosor, 0, java.awt.Color.BLACK));
        MenuLateral.setBorder(BorderFactory.createMatteBorder(0, 0, 0, grosor, java.awt.Color.BLACK)); // importante para que no se duplique

        Contenido.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, java.awt.Color.BLACK));
        Fondo.add(MenuLateral, BorderLayout.WEST);

        JPanel derecha = new JPanel(new BorderLayout(0, 0));
        derecha.setBorder(new EmptyBorder(0,0,0,0));
        derecha.add(MenuSuperior, BorderLayout.NORTH);
        derecha.add(Contenido, BorderLayout.CENTER);
        

        Fondo.add(derecha, BorderLayout.CENTER);

        Fondo.revalidate();
        Fondo.repaint();

        // Centrar título
        MenuSuperior.removeAll();
        MenuSuperior.setLayout(new BorderLayout());
        MenuSuperior.add(TextoMenuSuperior, BorderLayout.CENTER);
        TextoMenuSuperior.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        

        // ARMAR GRILLA
        ImagenesHelper.armarMenuEnGrilla(
        Contenido,
        new JButton[] {
            VerStockBoton, AumentarStockBoton, DisminuirStockBoton
        },
        3,   // columnas
        30,  // gap horizontal
        30,  // gap vertical
        25   // padding
        );

        // 2) Seteo tamaño consistente (opcional, pero queda muy pro)
        ImagenesHelper.setTamanoTarjeta(VerStockBoton, 220, 140);
        ImagenesHelper.setTamanoTarjeta(AumentarStockBoton, 220, 140);
        ImagenesHelper.setTamanoTarjeta(DisminuirStockBoton, 220, 140);
        
        // 3) Iconos escalados + texto centrado
        ImagenesHelper.configurarBotonTarjeta(VerStockBoton, "Ver Stock", "/Imagenes/VerStockBoton.png", 64, 64);
        ImagenesHelper.configurarBotonTarjeta(AumentarStockBoton, "Comprar Item", "/Imagenes/ComprarItemBoton.png", 64, 64);
        ImagenesHelper.configurarBotonTarjeta(DisminuirStockBoton, "Vender Item", "/Imagenes/VenderItemBoton.png", 64, 64);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        MenuLateral = new PanelLateral();
        VenderItem1 = new javax.swing.JButton();
        MenuSuperior = new javax.swing.JPanel();
        TextoMenuSuperior = new javax.swing.JLabel();
        Contenido = new PanelDeFondo("/Imagenes/Fondo.png");
        VerStockBoton = new javax.swing.JButton();
        AumentarStockBoton = new javax.swing.JButton();
        DisminuirStockBoton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setPreferredSize(new java.awt.Dimension(800, 500));
        Fondo.setRequestFocusEnabled(false);

        MenuLateral.setBackground(new java.awt.Color(51, 153, 255));
        MenuLateral.setPreferredSize(new java.awt.Dimension(200, 500));
        MenuLateral.setRequestFocusEnabled(false);

        VenderItem1.setForeground(new java.awt.Color(0, 0, 0));
        VenderItem1.setBorder(null);
        VenderItem1.setBorderPainted(false);
        VenderItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VenderItem1.addActionListener(this::VenderItem1ActionPerformed);

        javax.swing.GroupLayout MenuLateralLayout = new javax.swing.GroupLayout(MenuLateral);
        MenuLateral.setLayout(MenuLateralLayout);
        MenuLateralLayout.setHorizontalGroup(
            MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLateralLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(VenderItem1, javax.swing.GroupLayout.DEFAULT_SIZE, 7, Short.MAX_VALUE)
                .addGap(63, 63, 63))
        );
        MenuLateralLayout.setVerticalGroup(
            MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLateralLayout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addComponent(VenderItem1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MenuSuperior.setBackground(new java.awt.Color(0, 102, 255));

        TextoMenuSuperior.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        TextoMenuSuperior.setForeground(new java.awt.Color(255, 255, 255));
        TextoMenuSuperior.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextoMenuSuperior.setText("MENU STOCK");

        javax.swing.GroupLayout MenuSuperiorLayout = new javax.swing.GroupLayout(MenuSuperior);
        MenuSuperior.setLayout(MenuSuperiorLayout);
        MenuSuperiorLayout.setHorizontalGroup(
            MenuSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuSuperiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TextoMenuSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        MenuSuperiorLayout.setVerticalGroup(
            MenuSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuSuperiorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(TextoMenuSuperior)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        Contenido.setBackground(new java.awt.Color(204, 204, 204));
        Contenido.setPreferredSize(new java.awt.Dimension(700, 320));
        Contenido.setVerifyInputWhenFocusTarget(false);

        VerStockBoton.setBackground(new java.awt.Color(29, 63, 243));
        VerStockBoton.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        VerStockBoton.setForeground(new java.awt.Color(255, 255, 255));
        VerStockBoton.setText("Ver Stock");
        VerStockBoton.setBorder(new javax.swing.border.MatteBorder(null));
        VerStockBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VerStockBoton.addActionListener(this::VerStockBotonActionPerformed);

        AumentarStockBoton.setBackground(new java.awt.Color(204, 102, 255));
        AumentarStockBoton.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        AumentarStockBoton.setForeground(new java.awt.Color(255, 255, 255));
        AumentarStockBoton.setText("Comprar Item");
        AumentarStockBoton.setBorder(new javax.swing.border.MatteBorder(null));
        AumentarStockBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AumentarStockBoton.addActionListener(this::AumentarStockBotonActionPerformed);

        DisminuirStockBoton.setBackground(new java.awt.Color(204, 102, 255));
        DisminuirStockBoton.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        DisminuirStockBoton.setForeground(new java.awt.Color(255, 255, 255));
        DisminuirStockBoton.setText("Vender Item");
        DisminuirStockBoton.setBorder(new javax.swing.border.MatteBorder(null));
        DisminuirStockBoton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DisminuirStockBoton.addActionListener(this::DisminuirStockBotonActionPerformed);

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VerStockBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(AumentarStockBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(DisminuirStockBoton, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VerStockBoton)
                    .addComponent(AumentarStockBoton)
                    .addComponent(DisminuirStockBoton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(MenuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MenuSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuLateral, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(MenuSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(Fondo, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void VenderItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenderItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VenderItem1ActionPerformed

    private void VerStockBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerStockBotonActionPerformed
        JPanel verStock = new VerStockJPanel();
        FramePrincipal frame = (FramePrincipal) javax.swing.SwingUtilities.getWindowAncestor(this);
        frame.cambiarFondo(verStock);
    }//GEN-LAST:event_VerStockBotonActionPerformed

    private void AumentarStockBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AumentarStockBotonActionPerformed
        JPanel  comprarItem = new ComprarItemJPanel();
        FramePrincipal frame = (FramePrincipal) javax.swing.SwingUtilities.getWindowAncestor(this);
        frame.cambiarFondo(comprarItem);
    }//GEN-LAST:event_AumentarStockBotonActionPerformed

    private void DisminuirStockBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisminuirStockBotonActionPerformed
        JPanel venderItem = new VenderItemJPanel();
        FramePrincipal frame = (FramePrincipal) javax.swing.SwingUtilities.getWindowAncestor(this);
        frame.cambiarFondo(venderItem);
    }//GEN-LAST:event_DisminuirStockBotonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AumentarStockBoton;
    private javax.swing.JPanel Contenido;
    private javax.swing.JButton DisminuirStockBoton;
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel MenuLateral;
    private javax.swing.JPanel MenuSuperior;
    private javax.swing.JLabel TextoMenuSuperior;
    private javax.swing.JButton VenderItem1;
    private javax.swing.JButton VerStockBoton;
    // End of variables declaration//GEN-END:variables
}
