/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.PanelesInternos;

import Persistencia.Clases.Item;
import Persistencia.ManejadorDePersistencia;

/**
 *
 * @author Santi-kun
 */
public class CrearItemJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CrearItem
     */
    public CrearItemJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombreLbl = new javax.swing.JLabel();
        DescrpcionLbl = new javax.swing.JLabel();
        DescripcionContenido = new javax.swing.JTextField();
        Imagen = new javax.swing.JLabel();
        ImagenContenido = new javax.swing.JButton();
        Aceptar = new javax.swing.JButton();
        NombreContenido = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        NombreLbl.setText("Nombre:");

        DescrpcionLbl.setText("Descrpción:");

        Imagen.setText("Imágen:");

        ImagenContenido.setText("Seleccionar:");
        ImagenContenido.setBorder(null);
        ImagenContenido.setBorderPainted(false);
        ImagenContenido.addActionListener(this::ImagenContenidoActionPerformed);

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(this::AceptarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Aceptar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DescrpcionLbl)
                            .addComponent(Imagen)
                            .addComponent(NombreLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DescripcionContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(ImagenContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NombreContenido))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreLbl)
                    .addComponent(NombreContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DescrpcionLbl)
                    .addComponent(DescripcionContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Imagen)
                    .addComponent(ImagenContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Aceptar)
                .addContainerGap(122, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        String nombre = NombreContenido.getText().trim();
        String descripcion = DescripcionContenido.getText().trim();
        String rutaImagenSeleccionada = null;
        String imagen = rutaImagenSeleccionada; 
        if (nombre.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "El nombre es obligatorio");
        return;
        }
        if (imagen == null) {imagen = "";}
        Item nuevo = new Item(nombre, descripcion, imagen);
        try {
        
        ManejadorDePersistencia MDP = ManejadorDePersistencia.getInstancia();
        MDP.persistirItem(nuevo);
        javax.swing.JOptionPane.showMessageDialog(this, "Item creado OK");
        
        // limpiar campos
        NombreContenido.setText("");
        DescripcionContenido.setText("");
        rutaImagenSeleccionada = null;

    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error creando item: " + ex.getMessage());
        ex.printStackTrace();
    }

    }//GEN-LAST:event_AceptarActionPerformed

    private void ImagenContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImagenContenidoActionPerformed
  
    }//GEN-LAST:event_ImagenContenidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JTextField DescripcionContenido;
    private javax.swing.JLabel DescrpcionLbl;
    private javax.swing.JLabel Imagen;
    private javax.swing.JButton ImagenContenido;
    private javax.swing.JTextField NombreContenido;
    private javax.swing.JLabel NombreLbl;
    // End of variables declaration//GEN-END:variables
}
