/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.PanelesInternos;

/**
 *
 * @author Santi-kun
 */
public class CrearProveedor extends javax.swing.JPanel {

    /**
     * Creates new form CrearProveedor
     */
    public CrearProveedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombreLbl = new javax.swing.JLabel();
        NombreContenido = new javax.swing.JTextField();
        ContactoLbl = new javax.swing.JLabel();
        ContactoContenido = new javax.swing.JTextField();
        UbicacionContenido = new javax.swing.JTextField();
        UbicacionLbl = new javax.swing.JLabel();
        DescripcionLbl = new javax.swing.JLabel();
        DescripcionContenido = new javax.swing.JTextField();
        ImagenLbl = new javax.swing.JLabel();
        ImagenContenido = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(0, 320));
        setRequestFocusEnabled(false);

        NombreLbl.setText("Nombre:");

        NombreContenido.addActionListener(this::NombreContenidoActionPerformed);

        ContactoLbl.setText("Contacto:");

        ContactoContenido.addActionListener(this::ContactoContenidoActionPerformed);

        UbicacionContenido.addActionListener(this::UbicacionContenidoActionPerformed);

        UbicacionLbl.setText("Ubicación");

        DescripcionLbl.setText("Descripción:");

        DescripcionContenido.addActionListener(this::DescripcionContenidoActionPerformed);

        ImagenLbl.setText("Imágen:");

        ImagenContenido.setText("Seleccionar");
        ImagenContenido.setBorder(null);
        ImagenContenido.setBorderPainted(false);
        ImagenContenido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImagenContenido.addActionListener(this::ImagenContenidoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UbicacionLbl)
                    .addComponent(DescripcionLbl)
                    .addComponent(ContactoLbl)
                    .addComponent(NombreLbl)
                    .addComponent(ImagenLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(UbicacionContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContactoContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DescripcionContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ImagenContenido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombreContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContactoContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContactoLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UbicacionContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UbicacionLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DescripcionContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DescripcionLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagenLbl)
                    .addComponent(ImagenContenido))
                .addContainerGap(142, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NombreContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreContenidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreContenidoActionPerformed

    private void ContactoContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactoContenidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactoContenidoActionPerformed

    private void UbicacionContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbicacionContenidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UbicacionContenidoActionPerformed

    private void DescripcionContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescripcionContenidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionContenidoActionPerformed

    private void ImagenContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImagenContenidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImagenContenidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ContactoContenido;
    private javax.swing.JLabel ContactoLbl;
    private javax.swing.JTextField DescripcionContenido;
    private javax.swing.JLabel DescripcionLbl;
    private javax.swing.JButton ImagenContenido;
    private javax.swing.JLabel ImagenLbl;
    private javax.swing.JTextField NombreContenido;
    private javax.swing.JLabel NombreLbl;
    private javax.swing.JTextField UbicacionContenido;
    private javax.swing.JLabel UbicacionLbl;
    // End of variables declaration//GEN-END:variables
}
