/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.PanelesInternos;

import GUI.PanelesInternos.ComprarItem.ComprarItemJPanel;
import GUI.FramePrincipal;
import GUI.GUIController;
import GUI.PanelesPRINCIPALES.PanelDeConfiguracion;
import Persistencia.Clases.Proveedor;
import Persistencia.ManejadorDePersistencia;
import javax.swing.JPanel;

/**
 *
 * @author Santi-kun
 */
public class CrearProveedorJPanel extends javax.swing.JPanel {
    GUIController controller = new GUIController();
    /**
     * Creates new form CrearProveedor
     */
    public CrearProveedorJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        MenuSuperior = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Contenido = new javax.swing.JPanel();
        NombreLbl = new javax.swing.JLabel();
        NombreContenido = new javax.swing.JTextField();
        ContactoLbl = new javax.swing.JLabel();
        ContactoContenido = new javax.swing.JTextField();
        UbicacionContenido = new javax.swing.JTextField();
        UbicacionLbl = new javax.swing.JLabel();
        DescripcionLbl = new javax.swing.JLabel();
        DescripcionContenido = new javax.swing.JTextField();
        ImagenLbl = new javax.swing.JLabel();
        ImagenContenido = new javax.swing.JButton();
        ACEPTAR = new javax.swing.JButton();
        MenuLateral = new javax.swing.JPanel();
        CrearProveedor1 = new javax.swing.JButton();
        CrearItem1 = new javax.swing.JButton();
        Logo1 = new javax.swing.JLabel();
        Login1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Configuracion1 = new javax.swing.JButton();
        Configuracion2 = new javax.swing.JButton();
        ComprarItem = new javax.swing.JButton();
        VenderItem = new javax.swing.JButton();
        VenderItem1 = new javax.swing.JButton();
        Configuracion3 = new javax.swing.JButton();
        Configuracion4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(0, 320));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.BorderLayout());

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setPreferredSize(new java.awt.Dimension(800, 500));
        Fondo.setRequestFocusEnabled(false);

        MenuSuperior.setBackground(new java.awt.Color(0, 102, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Crear Proveedor");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ingrese los datos del nuevo proveedor");

        javax.swing.GroupLayout MenuSuperiorLayout = new javax.swing.GroupLayout(MenuSuperior);
        MenuSuperior.setLayout(MenuSuperiorLayout);
        MenuSuperiorLayout.setHorizontalGroup(
            MenuSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuSuperiorLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuSuperiorLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(77, 77, 77))
        );
        MenuSuperiorLayout.setVerticalGroup(
            MenuSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuSuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        Contenido.setBackground(new java.awt.Color(204, 204, 204));
        Contenido.setPreferredSize(new java.awt.Dimension(700, 320));
        Contenido.setVerifyInputWhenFocusTarget(false);

        NombreLbl.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        NombreLbl.setForeground(new java.awt.Color(0, 0, 0));
        NombreLbl.setText("Nombre:");

        NombreContenido.addActionListener(this::NombreContenidoActionPerformed);

        ContactoLbl.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        ContactoLbl.setForeground(new java.awt.Color(0, 0, 0));
        ContactoLbl.setText("Contacto:");

        ContactoContenido.addActionListener(this::ContactoContenidoActionPerformed);

        UbicacionContenido.addActionListener(this::UbicacionContenidoActionPerformed);

        UbicacionLbl.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        UbicacionLbl.setForeground(new java.awt.Color(0, 0, 0));
        UbicacionLbl.setText("Ubicación");

        DescripcionLbl.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        DescripcionLbl.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionLbl.setText("Descripción:");

        DescripcionContenido.addActionListener(this::DescripcionContenidoActionPerformed);

        ImagenLbl.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        ImagenLbl.setForeground(new java.awt.Color(0, 0, 0));
        ImagenLbl.setText("Imágen (opcional):");

        ImagenContenido.setText("Seleccionar");
        ImagenContenido.setBorder(null);
        ImagenContenido.setBorderPainted(false);
        ImagenContenido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ImagenContenido.addActionListener(this::ImagenContenidoActionPerformed);

        ACEPTAR.setBackground(new java.awt.Color(0, 102, 255));
        ACEPTAR.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        ACEPTAR.setForeground(new java.awt.Color(255, 255, 255));
        ACEPTAR.setText("ACEPTAR");
        ACEPTAR.setBorder(null);
        ACEPTAR.addActionListener(this::ACEPTARActionPerformed);

        javax.swing.GroupLayout ContenidoLayout = new javax.swing.GroupLayout(Contenido);
        Contenido.setLayout(ContenidoLayout);
        ContenidoLayout.setHorizontalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenidoLayout.createSequentialGroup()
                .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(ImagenContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContenidoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(ACEPTAR, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ContenidoLayout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ImagenLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(ContenidoLayout.createSequentialGroup()
                            .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(UbicacionLbl)
                                .addComponent(DescripcionLbl)
                                .addComponent(ContactoLbl)
                                .addComponent(NombreLbl))
                            .addGap(18, 18, 18)
                            .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(UbicacionContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ContactoContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NombreContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DescripcionContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        ContenidoLayout.setVerticalGroup(
            ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContenidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ImagenContenido)
                .addGap(18, 18, 18)
                .addComponent(ACEPTAR, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ContenidoLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NombreContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(NombreLbl))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ContactoContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ContactoLbl))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(UbicacionContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(UbicacionLbl))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(ContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DescripcionContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DescripcionLbl))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(ImagenLbl)
                    .addContainerGap(36, Short.MAX_VALUE)))
        );

        MenuLateral.setBackground(new java.awt.Color(51, 153, 255));
        MenuLateral.setPreferredSize(new java.awt.Dimension(200, 500));
        MenuLateral.setRequestFocusEnabled(false);

        CrearProveedor1.setForeground(new java.awt.Color(0, 0, 0));
        CrearProveedor1.setText("Crear Proveedor (ok)");
        CrearProveedor1.setBorder(null);
        CrearProveedor1.setBorderPainted(false);
        CrearProveedor1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CrearProveedor1.addActionListener(this::CrearProveedor1ActionPerformed);

        CrearItem1.setForeground(new java.awt.Color(0, 0, 0));
        CrearItem1.setText("Crear Item (ok)");
        CrearItem1.setBorder(null);
        CrearItem1.setBorderPainted(false);
        CrearItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CrearItem1.addActionListener(this::CrearItem1ActionPerformed);

        Logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TelecomLogo.png"))); // NOI18N

        Login1.setForeground(new java.awt.Color(0, 0, 0));
        Login1.setText("Iniciar Sesion (ok)");
        Login1.setBorder(null);
        Login1.setBorderPainted(false);
        Login1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login1.addActionListener(this::Login1ActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ACCIONES");

        Configuracion1.setForeground(new java.awt.Color(0, 0, 0));
        Configuracion1.setText("Configuración (ok)");
        Configuracion1.setBorder(null);
        Configuracion1.setBorderPainted(false);
        Configuracion1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Configuracion1.addActionListener(this::Configuracion1ActionPerformed);

        Configuracion2.setForeground(new java.awt.Color(0, 0, 0));
        Configuracion2.setText("Historial");
        Configuracion2.setBorder(null);
        Configuracion2.setBorderPainted(false);
        Configuracion2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Configuracion2.addActionListener(this::Configuracion2ActionPerformed);

        ComprarItem.setForeground(new java.awt.Color(0, 0, 0));
        ComprarItem.setText("Comprar Item");
        ComprarItem.setBorder(null);
        ComprarItem.setBorderPainted(false);
        ComprarItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComprarItem.addActionListener(this::ComprarItemActionPerformed);

        VenderItem.setForeground(new java.awt.Color(0, 0, 0));
        VenderItem.setText("Vender Item");
        VenderItem.setBorder(null);
        VenderItem.setBorderPainted(false);
        VenderItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VenderItem.addActionListener(this::VenderItemActionPerformed);

        VenderItem1.setForeground(new java.awt.Color(0, 0, 0));
        VenderItem1.setBorder(null);
        VenderItem1.setBorderPainted(false);
        VenderItem1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VenderItem1.addActionListener(this::VenderItem1ActionPerformed);

        Configuracion3.setForeground(new java.awt.Color(0, 0, 0));
        Configuracion3.setText("Catálogo General");
        Configuracion3.setBorder(null);
        Configuracion3.setBorderPainted(false);
        Configuracion3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Configuracion3.addActionListener(this::Configuracion3ActionPerformed);

        Configuracion4.setForeground(new java.awt.Color(0, 0, 0));
        Configuracion4.setText("Catálogo por Proveedor");
        Configuracion4.setBorder(null);
        Configuracion4.setBorderPainted(false);
        Configuracion4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Configuracion4.addActionListener(this::Configuracion4ActionPerformed);

        javax.swing.GroupLayout MenuLateralLayout = new javax.swing.GroupLayout(MenuLateral);
        MenuLateral.setLayout(MenuLateralLayout);
        MenuLateralLayout.setHorizontalGroup(
            MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CrearItem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Login1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuLateralLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addComponent(VenderItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ComprarItem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MenuLateralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLateralLayout.createSequentialGroup()
                        .addComponent(Logo1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLateralLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(VenderItem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(63, 63, 63))))
            .addComponent(CrearProveedor1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Configuracion2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Configuracion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Configuracion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Configuracion4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuLateralLayout.setVerticalGroup(
            MenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLateralLayout.createSequentialGroup()
                .addComponent(Logo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Login1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CrearItem1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComprarItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VenderItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CrearProveedor1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Configuracion2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Configuracion3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Configuracion4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Configuracion1)
                .addGap(34, 34, 34)
                .addComponent(VenderItem1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(MenuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MenuSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addComponent(MenuSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(MenuLateral, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
        );

        add(Fondo, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void NombreContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreContenidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreContenidoActionPerformed

    private void ContactoContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactoContenidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactoContenidoActionPerformed

    private void UbicacionContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbicacionContenidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UbicacionContenidoActionPerformed

    private void DescripcionContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescripcionContenidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionContenidoActionPerformed

    private void ImagenContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImagenContenidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImagenContenidoActionPerformed

    private void CrearProveedor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearProveedor1ActionPerformed
        // Creo el panel CrearProveedor
        JPanel crearProveedorPanel = new CrearProveedorJPanel();
        FramePrincipal frame = (FramePrincipal) javax.swing.SwingUtilities.getWindowAncestor(this);
        frame.cambiarFondo(crearProveedorPanel);
    }//GEN-LAST:event_CrearProveedor1ActionPerformed

    private void CrearItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearItem1ActionPerformed
        JPanel crearItemPanel = new CrearItemJPanel();
        FramePrincipal frame = (FramePrincipal) javax.swing.SwingUtilities.getWindowAncestor(this);
        frame.cambiarFondo(crearItemPanel);
    }//GEN-LAST:event_CrearItem1ActionPerformed

    private void Login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login1ActionPerformed
        JPanel loginPanel = new LoginJPanel();
        FramePrincipal frame = (FramePrincipal) javax.swing.SwingUtilities.getWindowAncestor(this);
        frame.cambiarFondo(loginPanel);
    }//GEN-LAST:event_Login1ActionPerformed

    private void Configuracion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Configuracion1ActionPerformed
        JPanel configuracionPanel = new PanelDeConfiguracion();
        FramePrincipal frame = (FramePrincipal) javax.swing.SwingUtilities.getWindowAncestor(this);
        frame.cambiarFondo(configuracionPanel);
    }//GEN-LAST:event_Configuracion1ActionPerformed

    private void Configuracion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Configuracion2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Configuracion2ActionPerformed

    private void ComprarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarItemActionPerformed
    JPanel  comprarItem = new ComprarItemJPanel();
        FramePrincipal frame = (FramePrincipal) javax.swing.SwingUtilities.getWindowAncestor(this);
        frame.cambiarFondo(comprarItem);
    }//GEN-LAST:event_ComprarItemActionPerformed

    private void VenderItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenderItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VenderItemActionPerformed

    private void VenderItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VenderItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VenderItem1ActionPerformed

    private void Configuracion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Configuracion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Configuracion3ActionPerformed

    private void Configuracion4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Configuracion4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Configuracion4ActionPerformed

    private void ACEPTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACEPTARActionPerformed
      String nombreProveedor = NombreContenido.getText().trim();
      String contacto = ContactoContenido.getText().trim();
      String ubicacion = UbicacionContenido.getText().trim();
      String descripcion = DescripcionContenido.getText().trim();
      //Por ahora lo dejo asi hasta que configure las imagenes
      String imagen = "";
      
      if (nombreProveedor.isEmpty() || contacto.isEmpty() || ubicacion.isEmpty() || descripcion.isEmpty()) {
          javax.swing.JOptionPane.showMessageDialog(this, "Debe rellenar todos los campos");
          return;
          }
      
     Proveedor nuevoProveedor = new Proveedor(nombreProveedor, contacto, ubicacion, descripcion, imagen);
     try{
     ManejadorDePersistencia MDP = ManejadorDePersistencia.getInstancia();
     MDP.persistirProveedor(nuevoProveedor);
     javax.swing.JOptionPane.showMessageDialog(null, "Proveedor OK");
     //Limpio los campos de texto
     NombreContenido.setText("");
     ContactoContenido.setText("");
     UbicacionContenido.setText("");
     DescripcionContenido.setText("");
     } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(null, "Error creando Proveedor: " + ex.getMessage());
        ex.printStackTrace();
     }
    }//GEN-LAST:event_ACEPTARActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACEPTAR;
    private javax.swing.JButton ComprarItem;
    private javax.swing.JButton Configuracion1;
    private javax.swing.JButton Configuracion2;
    private javax.swing.JButton Configuracion3;
    private javax.swing.JButton Configuracion4;
    private javax.swing.JTextField ContactoContenido;
    private javax.swing.JLabel ContactoLbl;
    private javax.swing.JPanel Contenido;
    private javax.swing.JButton CrearItem1;
    private javax.swing.JButton CrearProveedor1;
    private javax.swing.JTextField DescripcionContenido;
    private javax.swing.JLabel DescripcionLbl;
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton ImagenContenido;
    private javax.swing.JLabel ImagenLbl;
    private javax.swing.JButton Login1;
    private javax.swing.JLabel Logo1;
    private javax.swing.JPanel MenuLateral;
    private javax.swing.JPanel MenuSuperior;
    private javax.swing.JTextField NombreContenido;
    private javax.swing.JLabel NombreLbl;
    private javax.swing.JTextField UbicacionContenido;
    private javax.swing.JLabel UbicacionLbl;
    private javax.swing.JButton VenderItem;
    private javax.swing.JButton VenderItem1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
