/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import GUI.PanelesInternos.Items.CrearItemJPanel;
import GUI.PanelesInternos.Proveedores.CrearProveedorJPanel;
import GUI.PanelesInternos.LoginJPanel;
import Persistencia.Clases.Proveedor;
import Persistencia.ManejadorDePersistencia;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMTMaterialLighterIJTheme;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author Santi-kun
 */
public class FramePrincipal extends javax.swing.JFrame {
    GUIController controller = new GUIController();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FramePrincipal.class.getName());
    
    /*
    public void InitStyles(){
            //Hago que el label MensajeArriba tenga el valor h1 de texto gracias a FlatLaf
            MensajeArriba.putClientProperty( "FlatLaf.style", "font : 14 $light.font" );  
            MensajeArriba.setForeground(Color.black);
        }
    */
    
    //CONSTRUCTOR
    public FramePrincipal() {
        initComponents();
        //Al inicializal el frame principal le pido que cargue el Panel Principal tambien
        JPanel PanelPrincipal = new PanelPrincipal();
        controller.cambiarPanelGeneral(Fondo, PanelPrincipal);
        ManejadorDePersistencia MDP = ManejadorDePersistencia.getInstancia();
        Proveedor proveedorDefault = MDP.getOrCreateProveedorDefault();
    }
    //FUNCIONES
    public void cambiarFondo(JPanel panelNuevo){
        panelNuevo.setSize(Fondo.getSize());
        Fondo.removeAll();
        Fondo.add(panelNuevo, java.awt.BorderLayout.CENTER);
        Fondo.revalidate();
        Fondo.repaint();
    }
    /*
    public void cambiarContenido(JPanel panelNuevo) {
    panelNuevo.setSize(Contenido.getMaximumSize());
    panelNuevo.setLocation(0, 0);
    Contenido.removeAll();
    Contenido.add(panelNuevo);
    Contenido.revalidate();
    Contenido.repaint();
    }
       
    
    public void cambiarPanel(){
        JPanel panelNuevo = new PanelDeConfiguracion();
        panelNuevo.setSize(Fondo.getMaximumSize());
        Fondo.removeAll();
        Fondo.add(panelNuevo);
        Fondo.revalidate();
        Fondo.repaint();
    }
    
    public void cambiarPanelEntero(JPanel panelNuevo){
        panelNuevo.setSize(this.getMaximumSize()); //Obtengo el tamaño del JFrame 
        panelNuevo.setLocation(0, 0);
        //Borro el Menu, la Barra de Arriba, El Contenido y el Fondo, luego lo reemplazo por el nuevo panel
        Menu.removeAll();
        BarraArriba.removeAll();
        Contenido.removeAll();
        Fondo.removeAll();
        Fondo.add(panelNuevo);
        Fondo.revalidate();
        Fondo.repaint();
    }
    */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setPreferredSize(new java.awt.Dimension(800, 500));
        Fondo.setRequestFocusEnabled(false);
        Fondo.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 822, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //FlatMTMaterialLighterIJTheme.setup();
        
        
        //Este es otro tema, DeepOcean->
        //FlatMTMaterialDeepOceanIJTheme.setup();
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FramePrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    // End of variables declaration//GEN-END:variables
}
