/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Santi-kun
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        NombreEmpresa = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        ImagenDerecha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        InciarSesionLabel = new javax.swing.JLabel();
        UsuarioLabel = new javax.swing.JLabel();
        UsuarioValueLabel = new javax.swing.JLabel();
        ContraseñaLabel = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        BotonRecuadro = new javax.swing.JPanel();
        BotonTexto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreEmpresa.setFont(new java.awt.Font("Segoe UI Symbol", 0, 18)); // NOI18N
        NombreEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        NombreEmpresa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NombreEmpresa.setText("Telecom Ingeniería");
        Fondo.add(NombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 180, 30));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N
        Fondo.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 190, 160));

        ImagenDerecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/city.png"))); // NOI18N
        Fondo.add(ImagenDerecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 180, 320));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/favicon.png"))); // NOI18N
        Fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 50));

        InciarSesionLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        InciarSesionLabel.setForeground(new java.awt.Color(0, 0, 0));
        InciarSesionLabel.setText("INCIAR SESION");
        Fondo.add(InciarSesionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 220, 40));

        UsuarioLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        UsuarioLabel.setForeground(new java.awt.Color(0, 0, 0));
        UsuarioLabel.setText("USUARIO");
        Fondo.add(UsuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 410, 20));

        UsuarioValueLabel.setBackground(new java.awt.Color(204, 204, 204));
        UsuarioValueLabel.setText("Ingrese su nombre de usuario");
        Fondo.add(UsuarioValueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 410, -1));

        ContraseñaLabel.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        ContraseñaLabel.setForeground(new java.awt.Color(0, 0, 0));
        ContraseñaLabel.setText("CONTRASEÑA");
        Fondo.add(ContraseñaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 410, 20));

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(null);
        jPasswordField1.addActionListener(this::jPasswordField1ActionPerformed);
        Fondo.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 410, -1));

        BotonRecuadro.setBackground(new java.awt.Color(51, 204, 255));

        BotonTexto.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        BotonTexto.setForeground(new java.awt.Color(255, 255, 255));
        BotonTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BotonTexto.setText("ACEPTAR");
        BotonTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout BotonRecuadroLayout = new javax.swing.GroupLayout(BotonRecuadro);
        BotonRecuadro.setLayout(BotonRecuadroLayout);
        BotonRecuadroLayout.setHorizontalGroup(
            BotonRecuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonRecuadroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );
        BotonRecuadroLayout.setVerticalGroup(
            BotonRecuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonRecuadroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Fondo.add(BotonRecuadro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 //ajustarImagenAlLabel(ImagenDerecha, "/Imagenes/FondoTemporal.jpg");        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotonRecuadro;
    private javax.swing.JLabel BotonTexto;
    private javax.swing.JLabel ContraseñaLabel;
    private javax.swing.JPanel Fondo;
    private javax.swing.JLabel ImagenDerecha;
    private javax.swing.JLabel InciarSesionLabel;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel NombreEmpresa;
    private javax.swing.JLabel UsuarioLabel;
    private javax.swing.JLabel UsuarioValueLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables

private void ajustarImagenAlLabel(JLabel label, String resourcePath) {
        ImageIcon icon = new ImageIcon(getClass().getResource(resourcePath));

        int lw = label.getWidth();
        int lh = label.getHeight();
        if (lw <= 0 || lh <= 0) return;

        int iw = icon.getIconWidth();
        int ih = icon.getIconHeight();

        // Mantener proporción (fit)
        double scale = Math.max((double) lw / iw, (double) lh / ih);

        int nw = (int) (iw * scale);
        int nh = (int) (ih * scale);

        Image scaled = icon.getImage().getScaledInstance(nw, nh, Image.SCALE_SMOOTH);
        label.setIcon(new ImageIcon(scaled));

        label.setHorizontalAlignment(JLabel.CENTER);
        label.setVerticalAlignment(JLabel.CENTER);
    }


}
